### ISSUE TITLE
NanoVNA v2 to V2 plus bootloader issue

### ISSUE THREAD

**Issue by ra1nb0w** [eried/Research#4]
Hi,
I made the hardware modification following your [instruction](https://github.com/eried/Research/tree/master/NanoVNA/v2/upgrade_v2.2_to_plus) but if I load the V2plus firmware (stable and testing) it doesn't work. I get wrong data. You said that the bootloader is not needed anymore but probably is not true since many functions were moved to bootloader. Using V2 original version it works fine. Any suggestion?

thank you very much

**Comment by eried** [comment]
I am not sure, you should ask in discord :)

**Comment by ra1nb0w** [comment]
Confirmed, it doesn't work with the v2plus without the new bootloader and unfortunately there is no way to get it now. No sweep enhancement.

**Comment by eried** [comment]
:/ bummer

**Comment by ra1nb0w** [comment]
Yep. very annoying..

**Comment by ra1nb0w** [comment]
And since the bootloader is based on GPLv3 (from libopencm3 `Black Sphere Technologies CDC-ACM Demo DEMO`) they can't move to a closed source and not releasing the code. At least to anyone who request the source.
This is a very bad behavior that not respect others (﻿﻿independently of the motivations).

**Comment by eried** [comment]
yes I agree. It is a shady attempt to close it to an specific store that sells it
